#include "butterworth_filter.h"
#include <string.h> // For memset

// --- PASTE THE COEFFICIENTS GENERATED BY MATLAB HERE ---
// 4th-Order Butterworth, Fs=10Hz, Fc=20Hz
static const float b_coeffs_float[] = {
		0.167179268608490, 0.668717074433960, 1.003075611650940, 0.668717074433960, 0.167179268608490
};

static const float a_coeffs_float[] = {
		0.782095198023337, 0.679978526916300, 0.182675697753032, 0.030118875043169
};
// -------------------------------------------------------------------

void Butterworth_Init(Butterworth_Filter_t* filter) {
    // Clear state variables to zero
    memset(filter->z, 0, sizeof(filter->z));

    // Copy coefficients into the struct
    memcpy(filter->b, b_coeffs_float, sizeof(b_coeffs_float));

    // Copy denominator, skipping the first 'a' coefficient (a[0]=1)
    // and make them all negative require for calculation
    for (int i = 0; i < BUTTERWORTH_ORDER; ++i) {
        filter->a[i] = -a_coeffs_float[i];
    }
}

// Apply the filter using Direct Form II Transposed structure
float Butterworth_Apply(Butterworth_Filter_t* filter, float input) {
    // Calculate the output
    float output = filter->z[0] + filter->b[0] * input;

    // Update the state variables
    filter->z[0] = filter->z[1] + filter->b[1] * input + filter->a[0] * output;
    filter->z[1] = filter->z[2] + filter->b[2] * input + filter->a[1] * output;
    filter->z[2] = filter->z[3] + filter->b[3] * input + filter->a[2] * output;
    // The last state update is special
    filter->z[3] = 				  filter->b[4] * input + filter->a[3] * output;

    return output;
}


//Matlab code
/*% Filter Design Specifications
Fs = 100;       % Sampling Frequency (Hz)
N  = 4;         % Filter Order
Fc = 30;        % Cutoff Frequency (Hz)

% --- Design the 4th-Order Butterworth Lowpass Filter ---
[b, a] = butter(N, Fc/(Fs/2), 'low');*/
