//https://www.st.com/resource/en/application_note/an5305-digital-filter-implementation-with-the-fmac-using-stm32cubeg4-mcu-package-stmicroelectronics.pdf
//https://notblackmagic.com/bitsnpieces/dsp-accelerators/#fmac-filter-math-accelerator


//#include "lp_filter.h"
//#include "fmac.h" // Auto-generated by CubeMX
//
//// --- 1. Coefficients and Parameters from MATLAB ---
//// --- PASTE YOUR 10TH-ORDER GENERATED VALUES HERE ---
//#define FMAC_R_SHIFT 5 // Example value, use the one from your MATLAB script
//
//static const float b_coeffs_float[] = {0.002005828332847, 0.020058283328475, 0.090262274978136,
//										0.240699399941695, 0.421223949897967, 0.505468739877560,
//										0.421223949897967, 0.240699399941695, 0.090262274978136,
//										0.020058283328475, 0.002005828332847};
//static const float a_coeffs_float[] = {0.015625000000000, 0.093556087965885, 0.260503020671917,
//										0.441543560940634, 0.502496195120228, 0.400027337453959,
//										0.225088866034497, 0.088235536627070, 0.023026999015217,
//										0.003608114779094, 0.000257494227299};
//// -----------------------------------------------------
//
//// --- 2. Arrays to hold Q1.15 fixed-point coefficients ---
//static int16_t coeff_B[11]; //Size is N+1 = 11
//static int16_t coeff_A[10]; //N = 10 (a[1] to a[10])
//
//void FMAC_Filter_Init(void)
//{
//    // --- 3. Convert float coefficients to Q1.15 format ---
//    for (int i = 0; i < 11; i++) {
//        coeff_B[i] = (int16_t)(b_coeffs_float[i] * 32767.0f);
//    }
//    for (int i = 0; i < 10; i++) {
//        // The FMAC HAL often expects negated 'a' coefficients. Skip a_coeffs_float[0].
//        coeff_A[i] = (int16_t)(-a_coeffs_float[i + 1] * 32767.0f);
//    }
//
//    // --- 4. Configure the FMAC Hardware ---
//    FMAC_FilterConfigTypeDef sFilterConfig;
//
//    sFilterConfig.InputBaseAddress  = FMAC_BUFFER_A;
//    sFilterConfig.InputBufferSize   = 1;
//    sFilterConfig.InputThreshold    = 1;
//    sFilterConfig.CoeffBaseAddress  = FMAC_BUFFER_B;
//    sFilterConfig.CoeffBufferSize   = sizeof(coeff_B)/sizeof(int16_t) + sizeof(coeff_A)/sizeof(int16_t);
//    sFilterConfig.OutputBaseAddress = FMAC_BUFFER_C;
//    sFilterConfig.OutputBufferSize  = 1;
//    sFilterConfig.OutputThreshold   = 1;
//    sFilterConfig.pCoeffB           = coeff_B;
//    sFilterConfig.CoeffBSize        = sizeof(coeff_B) / sizeof(int16_t); // Now 11
//    sFilterConfig.pCoeffA           = coeff_A;
//    sFilterConfig.CoeffASize        = sizeof(coeff_A) / sizeof(int16_t); // Now 10
//    sFilterConfig.Filter            = FMAC_FILTER_IIR;
//    sFilterConfig.InputAccess       = FMAC_BUFFER_ACCESS_SINGLE;
//    sFilterConfig.OutputAccess      = FMAC_BUFFER_ACCESS_SINGLE;
//    sFilterConfig.Clip              = FMAC_CLIP_ENABLE;
//    sFilterConfig.P                 = sizeof(coeff_A) / sizeof(int16_t); //Denominator order is  10
//    sFilterConfig.Q                 = (sizeof(coeff_B) / sizeof(int16_t)) - 1; //Numerator order is now 10
//    sFilterConfig.R                 = FMAC_R_SHIFT; // Post-shift value from normalization
//
//    if (HAL_FMAC_FilterConfig(&hfmac, &sFilterConfig) != HAL_OK) {
//        Error_Handler();
//    }
//}
//
//// The FMAC_Filter_Apply function remains exactly the same as before
//int16_t FMAC_Filter_Apply(int16_t input_sample)
//{
//    int16_t output_sample;
//
//    HAL_FMAC_FilterLoad(&hfmac, &input_sample, 1);
//    HAL_FMAC_FilterStart(&hfmac, &output_sample, 1);
//    HAL_FMAC_PollFilterData(&hfmac, 10);
//
//    return output_sample;
//}




//MATLAB CODE
/*% Filter Design Specifications
Fs = 100;      % Sampling Frequency (Hz), from your 2kHz PID loop
N  = 10;        % <--- CHANGED: Filter Order is now 10
Fc = 40;       % Cutoff Frequency (Hz)

% --- Design the 10th-Order Butterworth Lowpass Filter ---
[b, a] = butter(N, Fc/(Fs/2), 'low');

% --- NORMALIZATION and SCALING (Based on AN5305 Section 2.5.3) ---
% Find the absolute largest coefficient to determine the scaling factor
max_coeff = max(max(abs(b)), max(abs(a)));

% Find the smallest power-of-two scaling factor (knorm = 1 / 2^n)
n_shift = 0;
while (max_coeff / (2^n_shift)) >= 1.0
    n_shift = n_shift + 1;
end
knorm_divisor = 2^n_shift;

% Apply the scaling factor to both numerator and denominator coefficients
b_scaled = b / knorm_divisor;
a_scaled = a / knorm_divisor;

% --- Display the results for C code ---
fprintf('// 10th-Order Butterworth, Fs=2000Hz, Fc=100Hz\n');
fprintf('// NORMALIZED AND SCALED FOR FMAC\n\n');

% The R parameter for the FMAC configuration is our shift value 'n'
fprintf('#define FMAC_R_SHIFT %d\n\n', n_shift);

% Display 'b' coefficients (11 values for 10th order)
fprintf('static const float b_coeffs_float[] = {');
fprintf('%.15f, ', b_scaled);
fprintf('};\n');

% Display 'a' coefficients (11 values for 10th order)
fprintf('static const float a_coeffs_float[] = {');
fprintf('%.15f, ', a_scaled);
fprintf('};\n');*/
